package com.tools.auth.exception;

public enum ErrorCode {
    EMAIL_ALREADY_EXISTS,
    EMAIL_NOT_VERIFIED,
    INVALID_CREDENTIALS,
    VALIDATION_ERROR,
    INVALID_RESET_CODE,
    RESET_CODE_EXPIRED,
    RESET_CODE_NOT_FOUND,
    INVALID_RESET_TOKEN,
    INVALID_ACTIVATION_CODE,
    ACTIVATION_CODE_EXPIRED,
    ACTIVATION_CODE_NOT_FOUND,
    UNAUTHORIZED
}
